"""Export utilities — CSV and PDF report generation."""

import csv
import io
import logging
from typing import Any

logger = logging.getLogger(__name__)


def export_analysis_csv(analysis: dict) -> str:
    """Generate a CSV string from an analysis result."""
    result = analysis.get("analysis_result") or {}
    issues = result.get("issues", [])

    output = io.StringIO()
    writer = csv.writer(output)

    writer.writerow([
        "AI Cloud Cost Detective — Report Export",
    ])
    writer.writerow([
        f"Analysis ID: {analysis.get('id', '')}",
    ])
    writer.writerow([
        f"Cloud: {analysis.get('cloud_provider', '').upper()}",
        f"Date: {analysis.get('created_at', '')}",
    ])
    writer.writerow([])

    writer.writerow([
        "Total Resources", "Issues Found",
        "Est. Monthly Savings", "Est. Annual Savings",
    ])
    writer.writerow([
        result.get("total_resources", 0),
        result.get("issues_found", 0),
        f"${result.get('estimated_monthly_savings', 0):.2f}",
        f"${result.get('estimated_annual_savings', 0):.2f}",
    ])
    writer.writerow([])
    writer.writerow([
        "Summary", result.get("summary", ""),
    ])
    writer.writerow([])
    writer.writerow([
        "Service", "Resource", "Region", "Account",
        "Issue Type", "Severity", "Explanation",
        "Fix Command", "Est. Monthly Savings",
    ])

    for issue in issues:
        writer.writerow([
            issue.get("service", ""),
            issue.get("resource_name", ""),
            issue.get("region", ""),
            issue.get("account_id", ""),
            issue.get("issue_type", ""),
            issue.get("severity", ""),
            issue.get("explanation", ""),
            issue.get("fix_command", ""),
            issue.get("potential_monthly_savings", 0),
        ])

    if not issues:
        writer.writerow(["No cost issues found."])

    writer.writerow([])
    writer.writerow(["Generated by AI Cloud Cost Detective"])

    return output.getvalue()


def export_cost_data_csv(cost_data: dict) -> str:
    """Generate a CSV string from cost explorer data."""
    output = io.StringIO()
    writer = csv.writer(output)

    writer.writerow(["AWS Cost Report"])
    writer.writerow(["Period", cost_data.get("period", {}).get("start", ""),
                     "to", cost_data.get("period", {}).get("end", "")])
    writer.writerow(["Total Spend", cost_data.get("total_spend", 0)])
    writer.writerow(["Projected Monthly", cost_data.get("projected_monthly_cost", 0)])
    writer.writerow([])

    writer.writerow(["Top Services by Cost"])
    writer.writerow(["Service", "Total", "Percentage"])
    for svc in cost_data.get("top_services", []):
        writer.writerow([svc["name"], svc["total"], f"{svc['percentage']}%"])

    writer.writerow([])
    writer.writerow(["Daily Costs"])
    writer.writerow(["Date", "Total"])
    for day in cost_data.get("daily_costs", []):
        writer.writerow([day["date"], day["total"]])

    return output.getvalue()
