"""
Comprehensive Free Tier information for AWS, Azure, and GCP.

Includes:
- All free tier eligible services
- Usage limits (monthly and annual)
- Service categories and descriptions
- Cost beyond free tier
- Eligibility type (12-month, always-free, trials)
"""

from typing import Optional


# ════════════════════════════════════════════════════════════════════════════════
#  AWS FREE TIER
# ════════════════════════════════════════════════════════════════════════════════

AWS_FREE_TIER = {
    "compute": [
        {
            "service": "EC2",
            "full_name": "Amazon Elastic Compute Cloud",
            "type": "12-month",
            "category": "Compute",
            "monthly_limit": "750 hours",
            "annual_limit": "9,000 hours",
            "instance_types": "t2.micro or t3.micro (Linux)",
            "description": "Run virtual servers in the cloud. Free tier covers 750 hours/month of a single t2.micro or t3.micro Linux instance.",
            "beyond_free_tier": "~$0.0104-0.0116/hour ($7.59-8.47/month)",
            "notes": "Windows instances are also available but consume free tier hours faster. Only 750 hours total across all regions.",
        },
        {
            "service": "Lambda",
            "full_name": "AWS Lambda",
            "type": "always-free",
            "category": "Compute",
            "monthly_limit": "1M requests + 400,000 GB-seconds",
            "annual_limit": "12M requests, 4.8M GB-seconds",
            "description": "Run code without servers. Free tier includes 1M requests and 400,000 GB-seconds of compute time per month.",
            "beyond_free_tier": "$0.20 per 1M requests, $0.0000166667 per GB-second",
            "notes": "Always free tier - no expiration. GB-seconds = (memory in GB) × (execution time in seconds).",
        },
        {
            "service": "ECS",
            "full_name": "Amazon Elastic Container Service",
            "type": "always-free",
            "category": "Compute",
            "monthly_limit": "No additional charge",
            "annual_limit": "No expiration",
            "description": "Run containers on EC2 instances you already pay for. ECS itself is free - you only pay for the underlying EC2 instances or Fargate.",
            "beyond_free_tier": "Fargate: $0.04048/vCPU/hour + $0.004445/GB/hour",
            "notes": "ECS with EC2 launch type is free. Fargate has its own pricing.",
        },
        {
            "service": "EKS",
            "full_name": "Amazon Elastic Kubernetes Service",
            "type": "12-month",
            "category": "Compute",
            "monthly_limit": "No cluster fee",
            "annual_limit": "No cluster fee for 12 months",
            "description": "Run Kubernetes clusters. EKS cluster fee ($0.10/hour) waived for 12 months.",
            "beyond_free_tier": "$0.10/hour ($73/month) for cluster control plane",
            "notes": "Control plane fee waived. Worker nodes (EC2 or Fargate) are billed separately.",
        },
    ],
    "storage": [
        {
            "service": "S3",
            "full_name": "Amazon Simple Storage Service",
            "type": "12-month",
            "category": "Storage",
            "monthly_limit": "5 GB Standard storage",
            "annual_limit": "60 GB-months",
            "additional_limits": {
                "get_requests": "20,000/month",
                "put_requests": "2,000/month",
            },
            "description": "Object storage. Free tier includes 5 GB of Standard storage, 20,000 GET requests, and 2,000 PUT requests per month.",
            "beyond_free_tier": "$0.023/GB Standard, $0.005/1,000 PUT requests",
            "notes": "Data transfer out beyond 100 GB/month is charged separately.",
        },
        {
            "service": "EBS",
            "full_name": "Amazon Elastic Block Store",
            "type": "12-month",
            "category": "Storage",
            "monthly_limit": "30 GB (gp2 or gp3)",
            "annual_limit": "360 GB-months",
            "description": "Block storage for EC2. Free tier includes 30 GB of gp2 or gp3 storage.",
            "beyond_free_tier": "$0.08-0.10/GB/month",
            "notes": "Only gp2 and gp3 volumes are free tier eligible. io1/io2 are not.",
        },
        {
            "service": "EFS",
            "full_name": "Amazon Elastic File System",
            "type": "12-month",
            "category": "Storage",
            "monthly_limit": "5 GB",
            "annual_limit": "60 GB-months",
            "description": "Managed NFS file system. Free tier includes 5 GB of storage.",
            "beyond_free_tier": "$0.30/GB Standard, $0.016/GB Infrequent Access",
            "notes": "Only Standard storage class is free tier eligible.",
        },
        {
            "service": "S3 Glacier",
            "full_name": "Amazon S3 Glacier",
            "type": "always-free",
            "category": "Storage",
            "monthly_limit": "10 GB",
            "annual_limit": "No expiration",
            "description": "Archival storage. Always free tier includes 10 GB of Glacier storage.",
            "beyond_free_tier": "$0.0036/GB (Glacier Instant), $0.004/GB (Flexible Retrieval)",
            "notes": "Retrieval costs apply. Instant Retrieval is most expensive but fastest.",
        },
    ],
    "databases": [
        {
            "service": "RDS",
            "full_name": "Amazon Relational Database Service",
            "type": "12-month",
            "category": "Databases",
            "monthly_limit": "750 hours db.t2.micro/db.t3.micro + 20 GB",
            "annual_limit": "9,000 hours, 240 GB-months",
            "engines": "MySQL, PostgreSQL, MariaDB, SQL Server Express",
            "description": "Managed relational databases. Free tier covers 750 hours/month of a db.t2.micro or db.t3.micro instance with 20 GB storage.",
            "beyond_free_tier": "~$0.017-0.034/hour ($12.41-24.82/month) + $0.10/GB",
            "notes": "SQL Server Express has limited free tier. Multi-AZ doubles costs.",
        },
        {
            "service": "DynamoDB",
            "full_name": "Amazon DynamoDB",
            "type": "always-free",
            "category": "Databases",
            "monthly_limit": "25 GB + 25 RCU + 25 WCU",
            "annual_limit": "No expiration",
            "description": "NoSQL database. Always free tier includes 25 GB storage, 25 Read Capacity Units, and 25 Write Capacity Units.",
            "beyond_free_tier": "$0.25/GB storage, $1.25/M on-demand read/write requests",
            "notes": "RCU and WCU are for provisioned capacity. On-demand pricing is different.",
        },
        {
            "service": "ElastiCache",
            "full_name": "Amazon ElastiCache",
            "type": "12-month",
            "category": "Databases",
            "monthly_limit": "750 hours cache.t2.micro",
            "annual_limit": "9,000 hours",
            "engines": "Redis or Memcached",
            "description": "In-memory caching. Free tier covers 750 hours/month of a cache.t2.micro instance.",
            "beyond_free_tier": "~$0.017/hour ($12.41/month)",
            "notes": "Only cache.t2.micro is free tier eligible.",
        },
        {
            "service": "DocumentDB",
            "full_name": "Amazon DocumentDB",
            "type": "12-month",
            "category": "Databases",
            "monthly_limit": "750 hours db.t3.medium",
            "annual_limit": "9,000 hours",
            "description": "MongoDB-compatible database. Free tier includes 750 hours of db.t3.medium.",
            "beyond_free_tier": "~$0.068/hour ($49.64/month)",
            "notes": "Only available in certain regions.",
        },
    ],
    "networking": [
        {
            "service": "CloudFront",
            "full_name": "Amazon CloudFront",
            "type": "always-free",
            "category": "Networking",
            "monthly_limit": "1 TB transfer + 10M requests",
            "annual_limit": "12 TB, 120M requests",
            "description": "CDN service. Always free tier includes 1 TB data transfer out and 10M HTTP/HTTPS requests per month.",
            "beyond_free_tier": "$0.085/GB (first 10 TB), $0.01/10,000 requests",
            "notes": "Edge location pricing varies by region.",
        },
        {
            "service": "Route 53",
            "full_name": "Amazon Route 53",
            "type": "always-free",
            "category": "Networking",
            "monthly_limit": "50 hosted zones",
            "annual_limit": "No expiration",
            "description": "DNS service. Always free tier includes 50 hosted zones (first 50).",
            "beyond_free_tier": "$0.50/hosted zone/month",
            "notes": "Health checks and DNS queries are charged separately.",
        },
        {
            "service": "VPC",
            "full_name": "Amazon Virtual Private Cloud",
            "type": "always-free",
            "category": "Networking",
            "monthly_limit": "No additional charge",
            "annual_limit": "No expiration",
            "description": "Isolated network. VPC itself is free. You pay for resources launched within it.",
            "beyond_free_tier": "N/A - resources within VPC are billed separately",
            "notes": "NAT Gateway and VPC Endpoints have separate charges.",
        },
        {
            "service": "ELB",
            "full_name": "Elastic Load Balancing",
            "type": "12-month",
            "category": "Networking",
            "monthly_limit": "750 hours",
            "annual_limit": "9,000 hours",
            "types": "Classic, Application, Network",
            "description": "Load balancers. Free tier covers 750 hours/month of Classic, ALB, or NLB.",
            "beyond_free_tier": "$16-22/month + data processing charges",
            "notes": "ALB and NLB have higher base costs than Classic LB.",
        },
        {
            "service": "NAT Gateway",
            "full_name": "Amazon NAT Gateway",
            "type": "not-free",
            "category": "Networking",
            "monthly_limit": "NOT free tier eligible",
            "description": "NAT Gateways are NOT free tier eligible. They cost ~$32/month plus data processing.",
            "beyond_free_tier": "$32.40/month + $0.045/GB data processed",
            "notes": "Consider using a NAT instance (t3.medium ~$15/month) for dev/test environments.",
        },
    ],
    "messaging": [
        {
            "service": "SQS",
            "full_name": "Amazon Simple Queue Service",
            "type": "always-free",
            "category": "Messaging",
            "monthly_limit": "1M requests",
            "annual_limit": "12M requests",
            "description": "Message queuing. Always free tier includes 1M free requests per month.",
            "beyond_free_tier": "$0.40/1M requests (Standard), $0.80/1M (FIFO)",
            "notes": "FIFO queues cost twice as much per request.",
        },
        {
            "service": "SNS",
            "full_name": "Amazon Simple Notification Service",
            "type": "always-free",
            "category": "Messaging",
            "monthly_limit": "1M publishes + 100K HTTP deliveries",
            "annual_limit": "12M publishes, 1.2M HTTP deliveries",
            "description": "Pub/sub messaging. Always free tier includes 1M publishes and 100K HTTP deliveries per month.",
            "beyond_free_tier": "$0.50/1M publishes, $2.00/100K mobile pushes",
            "notes": "SMS and email deliveries are charged separately.",
        },
        {
            "service": "Kinesis",
            "full_name": "Amazon Kinesis",
            "type": "12-month",
            "category": "Messaging",
            "monthly_limit": "750 shard hours",
            "annual_limit": "9,000 shard hours",
            "description": "Data streaming. Free tier covers 750 shard hours/month (1 shard running 24/7).",
            "beyond_free_tier": "$0.015/shard-hour",
            "notes": "Data transfer and PUT payload are charged separately.",
        },
    ],
    "analytics": [
        {
            "service": "Athena",
            "full_name": "Amazon Athena",
            "type": "always-free",
            "category": "Analytics",
            "monthly_limit": "1 TB scanned per month",
            "annual_limit": "12 TB",
            "description": "Serverless query service. Always free tier includes 1 TB of data scanned per month.",
            "beyond_free_tier": "$5.00/TB scanned",
            "notes": "Result files stored in S3 are charged at S3 rates.",
        },
        {
            "service": "Glue",
            "full_name": "AWS Glue",
            "type": "12-month",
            "category": "Analytics",
            "monthly_limit": "1 million objects stored",
            "annual_limit": "12M objects",
            "description": "ETL service. Free tier covers 1 million objects stored in the AWS Glue Data Catalog.",
            "beyond_free_tier": "$1.00/1M objects, $0.44/DPU-hour",
            "notes": "Crawlers and ETL jobs are charged per DPU-hour.",
        },
        {
            "service": "EMR",
            "full_name": "Amazon EMR",
            "type": "12-month",
            "category": "Analytics",
            "monthly_limit": "No additional free tier",
            "description": "Big data processing. EMR is not free tier eligible but uses EC2 instances that may be.",
            "beyond_free_tier": "$0.0216/node/hour + EC2 costs",
            "notes": "EMR itself has no free tier, but EC2 instances within it may qualify.",
        },
    ],
    "ai_ml": [
        {
            "service": "SageMaker",
            "full_name": "Amazon SageMaker",
            "type": "12-month",
            "category": "AI/ML",
            "monthly_limit": "No free tier",
            "description": "Machine learning platform. No free tier available.",
            "beyond_free_tier": "Varies by instance type ($0.04-$30+/hour)",
            "notes": "Consider using Lambda or EC2 for ML inference instead.",
        },
        {
            "service": "Bedrock",
            "full_name": "Amazon Bedrock",
            "type": "not-free",
            "category": "AI/ML",
            "monthly_limit": "NOT free tier eligible",
            "description": "Foundation models API (Claude, Llama, etc.). No free tier. Pay per token usage.",
            "beyond_free_tier": "$0.0004-0.032/1K input tokens (varies by model)",
            "notes": "Bedrock Serverless Inference offers pay-per-use pricing but no free tier. For free AI, use the built-in rule engine or Ollama locally.",
        },
        {
            "service": "Rekognition",
            "full_name": "Amazon Rekognition",
            "type": "12-month",
            "category": "AI/ML",
            "monthly_limit": "5,000 images + 1,000 videos",
            "annual_limit": "60,000 images, 12,000 videos",
            "description": "Image and video analysis. Free tier includes 5,000 images and 1,000 videos per month for 12 months.",
            "beyond_free_tier": "$0.001/image, $0.10/video (first 10 min)",
            "notes": "Video analysis is significantly more expensive than images.",
        },
        {
            "service": "Comprehend",
            "full_name": "Amazon Comprehend",
            "type": "12-month",
            "category": "AI/ML",
            "monthly_limit": "50K units NLP + 5 hrs Textract",
            "annual_limit": "600K units, 60 hrs Textract",
            "description": "Natural language processing. Free tier includes 50,000 units/month of NLP features.",
            "beyond_free_tier": "$0.0001/unit (Key Phrases), $0.00025/unit (Sentiment)",
            "notes": "Custom models have different pricing.",
        },
    ],
    "security": [
        {
            "service": "IAM",
            "full_name": "AWS Identity and Access Management",
            "type": "always-free",
            "category": "Security",
            "monthly_limit": "No additional charge",
            "annual_limit": "No expiration",
            "description": "User and permission management. IAM is always free.",
            "beyond_free_tier": "N/A",
            "notes": "You pay for AWS resources, not IAM itself.",
        },
        {
            "service": "KMS",
            "full_name": "AWS Key Management Service",
            "type": "always-free",
            "category": "Security",
            "monthly_limit": "1 free customer-managed key",
            "annual_limit": "No expiration",
            "description": "Encryption key management. Always free tier includes 1 free customer-managed KMS key.",
            "beyond_free_tier": "$1/key/month + $0.03/10,000 requests",
            "notes": "AWS managed keys are free. Customer-managed keys cost $1/month after the first.",
        },
        {
            "service": "GuardDuty",
            "full_name": "Amazon GuardDuty",
            "type": "12-month",
            "category": "Security",
            "monthly_limit": "90 days free trial",
            "annual_limit": "90-day trial",
            "description": "Threat detection. Free 90-day trial for new accounts.",
            "beyond_free_tier": "$0.10/1M events, $0.25/GuardDuty Lite finding",
            "notes": "Trial is per-account. After trial, costs scale with activity.",
        },
    ],
    "management": [
        {
            "service": "CloudWatch",
            "full_name": "Amazon CloudWatch",
            "type": "always-free",
            "category": "Management",
            "monthly_limit": "5 GB logs + 10 metrics + 10 alarms",
            "annual_limit": "60 GB logs, 120 metrics, 120 alarms",
            "description": "Monitoring and observability. Always free tier includes 5 GB log ingestion, 10 custom metrics, and 10 alarms.",
            "beyond_free_tier": "$0.50/GB ingested, $0.30/metric, $0.10/alarm",
            "notes": "Dashboards cost $3.00/dashboard/month.",
        },
        {
            "service": "CloudFormation",
            "full_name": "AWS CloudFormation",
            "type": "always-free",
            "category": "Management",
            "monthly_limit": "No additional charge",
            "annual_limit": "No expiration",
            "description": "Infrastructure as code. CloudFormation is free - you pay only for AWS resources it creates.",
            "beyond_free_tier": "N/A - resources are billed separately",
            "notes": "Third-party resources may incur additional charges.",
        },
    ],
}


# ════════════════════════════════════════════════════════════════════════════════
#  AZURE FREE TIER
# ════════════════════════════════════════════════════════════════════════════════

AZURE_FREE_TIER = {
    "compute": [
        {
            "service": "Virtual Machines",
            "full_name": "Azure Virtual Machines",
            "type": "12-month",
            "category": "Compute",
            "monthly_limit": "750 hours B1s or B1ms",
            "annual_limit": "9,000 hours",
            "instance_types": "B1s (1 vCPU, 1 GB) or B1ms (1 vCPU, 2 GB)",
            "description": "Run Windows or Linux VMs. Free tier covers 750 hours/month of B1s or B1ms.",
            "beyond_free_tier": "$0.0104-0.0208/hour ($7.59-15.18/month)",
            "notes": "Linux instances are cheaper. Windows instances cost ~2x more.",
        },
        {
            "service": "Azure Functions",
            "full_name": "Azure Functions",
            "type": "always-free",
            "category": "Compute",
            "monthly_limit": "1M executions + 400,000 GB-seconds",
            "annual_limit": "No expiration",
            "description": "Serverless compute. Always free tier includes 1M executions and 400,000 GB-seconds.",
            "beyond_free_tier": "$0.20/1M executions, $0.000016/GB-second",
            "notes": "Consumption plan only. Premium plan has different pricing.",
        },
        {
            "service": "Azure Kubernetes Service",
            "full_name": "Azure Kubernetes Service (AKS)",
            "type": "always-free",
            "category": "Compute",
            "monthly_limit": "No cluster fee",
            "annual_limit": "No expiration",
            "description": "Managed Kubernetes. AKS control plane is free - you only pay for worker nodes.",
            "beyond_free_tier": "Worker nodes: $0.04-0.10/vCPU/hour",
            "notes": "Free tier includes free management plane. You pay for VM nodes.",
        },
    ],
    "storage": [
        {
            "service": "Blob Storage",
            "full_name": "Azure Blob Storage",
            "type": "12-month",
            "category": "Storage",
            "monthly_limit": "5 GB (LRS Hot)",
            "annual_limit": "60 GB-months",
            "description": "Object storage. Free tier includes 5 GB of LRS Hot storage.",
            "beyond_free_tier": "$0.018/GB (Hot), $0.01/GB (Cool), $0.002/GB (Archive)",
            "notes": "LRS = Locally Redundant Storage. GRS costs more.",
        },
        {
            "service": "Managed Disks",
            "full_name": "Azure Managed Disks",
            "type": "12-month",
            "category": "Storage",
            "monthly_limit": "64 GB P6 SSD or 128 GB S6",
            "annual_limit": "768 GB-months",
            "description": "Block storage for VMs. Free tier includes 64 GB P6 SSD or 128 GB S6.",
            "beyond_free_tier": "$0.07/GB (P6 SSD), $0.04/GB (S6 HDD)",
            "notes": "P6 is premium SSD (better performance). S6 is standard HDD.",
        },
        {
            "service": "Queue Storage",
            "full_name": "Azure Queue Storage",
            "type": "12-month",
            "category": "Storage",
            "monthly_limit": "100 GB",
            "annual_limit": "1,200 GB-months",
            "description": "Message queuing. Free tier includes 100 GB of queue storage.",
            "beyond_free_tier": "$0.00036/10K operations",
            "notes": "100 GB is a generous limit for most queue workloads.",
        },
    ],
    "databases": [
        {
            "service": "Azure SQL Database",
            "full_name": "Azure SQL Database",
            "type": "12-month",
            "category": "Databases",
            "monthly_limit": "250 GB DTU or 100K vCore seconds",
            "annual_limit": "3,000 GB-months",
            "description": "Managed SQL Server. Free tier includes 250 GB of DTU-based or 100K vCore seconds.",
            "beyond_free_tier": "$0.0068/DTU-hour, $0.20/vCore-hour",
            "notes": "Serverless tier auto-pauses when idle (saves costs).",
        },
        {
            "service": "Cosmos DB",
            "full_name": "Azure Cosmos DB",
            "type": "always-free",
            "category": "Databases",
            "monthly_limit": "1000 RU/s + 25 GB",
            "annual_limit": "No expiration",
            "description": "Multi-model database. Always free tier includes 1000 RU/s throughput and 25 GB storage.",
            "beyond_free_tier": "$0.008/100K RU/s, $0.25/GB",
            "notes": "Serverless mode has different pricing (per-operation).",
        },
        {
            "service": "Azure Cache for Redis",
            "full_name": "Azure Cache for Redis",
            "type": "12-month",
            "category": "Databases",
            "monthly_limit": "250 MB C0",
            "annual_limit": "3,000 MB-months",
            "description": "In-memory caching. Free tier includes 250 MB C0 cache.",
            "beyond_free_tier": "$0.024/hour ($17.52/month) for C0",
            "notes": "C0 is Basic tier. Standard/Premium tiers cost more.",
        },
    ],
    "networking": [
        {
            "service": "Bandwidth",
            "full_name": "Azure Bandwidth",
            "type": "12-month",
            "category": "Networking",
            "monthly_limit": "5 GB outbound",
            "annual_limit": "60 GB",
            "description": "Data transfer. Free tier includes 5 GB of outbound data transfer per month.",
            "beyond_free_tier": "$0.087/GB (first 10 TB)",
            "notes": "Inbound is always free. Only outbound is charged.",
        },
        {
            "service": "Public IP",
            "full_name": "Azure Public IP",
            "type": "12-month",
            "category": "Networking",
            "monthly_limit": "5 static IPs",
            "annual_limit": "60 IP-months",
            "description": "Public IP addresses. Free tier includes 5 static public IPs.",
            "beyond_free_tier": "$3.65/Standard, $1.46/Basic IP/month",
            "notes": "Dynamic IPs are free but change on restart.",
        },
        {
            "service": "Load Balancer",
            "full_name": "Azure Load Balancer",
            "type": "12-month",
            "category": "Networking",
            "monthly_limit": "5 rules",
            "annual_limit": "60 rule-months",
            "description": "Load balancing. Free tier includes 5 LB rules.",
            "beyond_free_tier": "$0.025/rule-hour, $0.0125/data processed GB",
            "notes": "Basic tier is free. Standard tier costs more.",
        },
    ],
    "ai_ml": [
        {
            "service": "Azure Cognitive Services",
            "full_name": "Azure Cognitive Services",
            "type": "12-month",
            "category": "AI/ML",
            "monthly_limit": "5,000 transactions",
            "annual_limit": "60,000 transactions",
            "description": "AI APIs (Vision, Speech, Language). Free tier includes 5,000 transactions/month.",
            "beyond_free_tier": "$1/1000 transactions (varies by API)",
            "notes": "Different APIs have different pricing tiers.",
        },
        {
            "service": "Azure Machine Learning",
            "full_name": "Azure Machine Learning",
            "type": "12-month",
            "category": "AI/ML",
            "monthly_limit": "Free tier workspace",
            "description": "ML platform. Free tier workspace with limited compute.",
            "beyond_free_tier": "$0.10-0.50/hour (compute), $0.001/transaction",
            "notes": "Free tier has limited compute hours and storage.",
        },
    ],
    "management": [
        {
            "service": "Azure Monitor",
            "full_name": "Azure Monitor",
            "type": "always-free",
            "category": "Management",
            "monthly_limit": "5 GB logs + 10 metrics",
            "annual_limit": "60 GB logs, 120 metrics",
            "description": "Monitoring and observability. Always free tier includes 5 GB log analytics and 10 metrics.",
            "beyond_free_tier": "$2.30/GB (first 10 GB), $0.30/metric",
            "notes": "Log Analytics workspace has first 5 GB free.",
        },
        {
            "service": "Azure Resource Manager",
            "full_name": "Azure Resource Manager",
            "type": "always-free",
            "category": "Management",
            "monthly_limit": "No additional charge",
            "annual_limit": "No expiration",
            "description": "Infrastructure management. ARM is free - you pay for resources it manages.",
            "beyond_free_tier": "N/A",
            "notes": "ARM templates and deployments are free.",
        },
    ],
}


# ════════════════════════════════════════════════════════════════════════════════
#  GCP FREE TIER
# ════════════════════════════════════════════════════════════════════════════════

GCP_FREE_TIER = {
    "compute": [
        {
            "service": "Compute Engine",
            "full_name": "Google Compute Engine",
            "type": "always-free",
            "category": "Compute",
            "monthly_limit": "1 non-shared CPU + 30 GB HDD + 1 GB egress",
            "annual_limit": "No expiration",
            "instance_types": "f1-micro or g1-small (us regions only)",
            "description": "VMs. Always free tier includes 1 non-shared CPU (f1-micro or g1-small) in us regions.",
            "beyond_free_tier": "$0.0042-0.0104/hour ($3.07-7.59/month)",
            "notes": "Only f1-micro and g1-small are always free. Other instances are not.",
        },
        {
            "service": "Cloud Functions",
            "full_name": "Google Cloud Functions",
            "type": "always-free",
            "category": "Compute",
            "monthly_limit": "2M invocations + 400K GB-seconds",
            "annual_limit": "No expiration",
            "description": "Serverless functions. Always free tier includes 2M invocations and 400K GB-seconds.",
            "beyond_free_tier": "$0.40/1M invocations, $0.0000025/GHz-second",
            "notes": "Generous free tier compared to AWS Lambda.",
        },
        {
            "service": "Cloud Run",
            "full_name": "Google Cloud Run",
            "type": "always-free",
            "category": "Compute",
            "monthly_limit": "2M requests + 360K GB-seconds",
            "annual_limit": "No expiration",
            "description": "Serverless containers. Always free tier includes 2M requests and 360K GB-seconds.",
            "beyond_free_tier": "$0.40/1M requests, $0.000024/vCPU-second",
            "notes": "180,000 vCPU-seconds free per month.",
        },
        {
            "service": "GKE",
            "full_name": "Google Kubernetes Engine",
            "type": "12-month",
            "category": "Compute",
            "monthly_limit": "1 zonal cluster control plane",
            "annual_limit": "No expiration for Autopilot",
            "description": "Managed Kubernetes. Autopilot clusters have free control plane. Standard clusters: $10/hour for control plane.",
            "beyond_free_tier": "$10/hour (Standard), $0.10/hour (Autopilot)",
            "notes": "Autopilot mode: control plane is free. Standard: $73/month.",
        },
    ],
    "storage": [
        {
            "service": "Cloud Storage",
            "full_name": "Google Cloud Storage",
            "type": "always-free",
            "category": "Storage",
            "monthly_limit": "5 GB (Standard, us regions)",
            "annual_limit": "No expiration",
            "description": "Object storage. Always free tier includes 5 GB of Standard storage in us regions.",
            "beyond_free_tier": "$0.020/GB (Standard), $0.010/GB (Nearline)",
            "notes": "Only us multi-region and specific us regions are free.",
        },
        {
            "service": "Persistent Disk",
            "full_name": "Google Compute Engine Persistent Disk",
            "type": "always-free",
            "category": "Storage",
            "monthly_limit": "30 GB HDD (us regions)",
            "annual_limit": "No expiration",
            "description": "Block storage. Always free tier includes 30 GB of HDD storage.",
            "beyond_free_tier": "$0.04/GB (pd-standard), $0.17/GB (pd-ssd)",
            "notes": "Only pd-standard (HDD) is free. SSD is not.",
        },
    ],
    "databases": [
        {
            "service": "Cloud SQL",
            "full_name": "Google Cloud SQL",
            "type": "12-month",
            "category": "Databases",
            "monthly_limit": "1 GB HDD (us regions)",
            "annual_limit": "12 GB-months",
            "description": "Managed relational databases. Free tier includes 1 GB of HDD storage for MySQL/PostgreSQL.",
            "beyond_free_tier": "$0.017/hour (db-f1-micro), $0.041/hour (db-g1-small)",
            "notes": "Only storage is free. Instance hours are not.",
        },
        {
            "service": "Firestore",
            "full_name": "Google Cloud Firestore",
            "type": "always-free",
            "category": "Databases",
            "monthly_limit": "1 GB storage + 50K reads + 20K writes",
            "annual_limit": "No expiration",
            "description": "NoSQL document database. Always free tier includes 1 GB storage and generous operations.",
            "beyond_free_tier": "$0.18/GB (storage), $0.06/100K reads, $0.18/100K writes",
            "notes": "Very generous free tier for small applications.",
        },
        {
            "service": "Memorystore",
            "full_name": "Google Memorystore for Redis",
            "type": "12-month",
            "category": "Databases",
            "monthly_limit": "1 GB Basic tier",
            "annual_limit": "12 GB-months",
            "description": "Managed Redis. Free tier includes 1 GB Basic tier.",
            "beyond_free_tier": "$0.029/hour (Basic), $0.058/hour (Standard)",
            "notes": "Only Basic tier is free. Standard has replication.",
        },
    ],
    "networking": [
        {
            "service": "Cloud CDN",
            "full_name": "Google Cloud CDN",
            "type": "always-free",
            "category": "Networking",
            "monthly_limit": "1 TB egress + 10M requests",
            "annual_limit": "No expiration",
            "description": "Content delivery. Always free tier includes 1 TB egress and 10M requests.",
            "beyond_free_tier": "$0.02-0.08/GB (varies by region)",
            "notes": "Very generous free tier for CDN.",
        },
        {
            "service": "Cloud DNS",
            "full_name": "Google Cloud DNS",
            "type": "always-free",
            "category": "Networking",
            "monthly_limit": "100K queries",
            "annual_limit": "No expiration",
            "description": "DNS hosting. Always free tier includes 100,000 queries per month.",
            "beyond_free_tier": "$0.20/zone/month, $0.40/1M queries",
            "notes": "Zone cost is $0.20/month after first zone.",
        },
        {
            "service": "Cloud NAT",
            "full_name": "Google Cloud NAT",
            "type": "always-free",
            "category": "Networking",
            "monthly_limit": "No additional charge",
            "annual_limit": "No expiration",
            "description": "NAT gateway. Cloud NAT itself is free - you pay for data processing.",
            "beyond_free_tier": "$0.044/GiB (data processing)",
            "notes": "Only data processing is charged. No gateway fee.",
        },
    ],
    "ai_ml": [
        {
            "service": "Cloud Vision API",
            "full_name": "Google Cloud Vision API",
            "type": "always-free",
            "category": "AI/ML",
            "monthly_limit": "1,000 units/month",
            "annual_limit": "No expiration",
            "description": "Image analysis. Always free tier includes 1,000 units per month.",
            "beyond_free_tier": "$1.50/1000 units (Label Detection)",
            "notes": "Different features have different unit costs.",
        },
        {
            "service": "Cloud Speech-to-Text",
            "full_name": "Google Cloud Speech-to-Text",
            "type": "always-free",
            "category": "AI/ML",
            "monthly_limit": "60 minutes/month",
            "annual_limit": "No expiration",
            "description": "Speech recognition. Always free tier includes 60 minutes per month.",
            "beyond_free_tier": "$0.006-0.016/15 seconds (varies by model)",
            "notes": "Standard model is cheapest. Premium model costs more.",
        },
        {
            "service": "Cloud Text-to-Speech",
            "full_name": "Google Cloud Text-to-Speech",
            "type": "always-free",
            "category": "AI/ML",
            "monthly_limit": "1 million characters/month",
            "annual_limit": "No expiration",
            "description": "Speech synthesis. Always free tier includes 1 million characters per month.",
            "beyond_free_tier": "$0.004/1000 characters (Standard), $0.016/1000 (WaveNet)",
            "notes": "WaveNet sounds more natural but costs 4x more.",
        },
    ],
    "management": [
        {
            "service": "Cloud Logging",
            "full_name": "Google Cloud Logging",
            "type": "always-free",
            "category": "Management",
            "monthly_limit": "50 GB logs",
            "annual_limit": "No expiration",
            "description": "Log management. Always free tier includes 50 GB of log storage.",
            "beyond_free_tier": "$0.50/GB (exceeding free tier)",
            "notes": "Very generous 50 GB free tier.",
        },
        {
            "service": "Cloud Monitoring",
            "full_name": "Google Cloud Monitoring",
            "type": "always-free",
            "category": "Management",
            "monthly_limit": "150 MB metrics",
            "annual_limit": "No expiration",
            "description": "Metrics and alerting. Always free tier includes 150 MB of metrics.",
            "beyond_free_tier": "$0.25/MB (exceeding free tier)",
            "notes": "Includes dashboards and alerting.",
        },
    ],
}


def get_free_tier(provider: str = "all") -> dict:
    """Get free tier information for a specific provider or all providers."""
    if provider == "aws":
        return {"aws": AWS_FREE_TIER}
    elif provider == "azure":
        return {"azure": AZURE_FREE_TIER}
    elif provider == "gcp":
        return {"gcp": GCP_FREE_TIER}
    else:
        return {
            "aws": AWS_FREE_TIER,
            "azure": AZURE_FREE_TIER,
            "gcp": GCP_FREE_TIER,
        }


def get_free_tier_summary(provider: str = "all") -> list:
    """Get a flat list of all free tier services with summary info."""
    providers = get_free_tier(provider)
    summary = []
    
    for prov, categories in providers.items():
        for category, services in categories.items():
            for svc in services:
                summary.append({
                    "provider": prov.upper(),
                    "service": svc["service"],
                    "full_name": svc.get("full_name", svc["service"]),
                    "type": svc["type"],
                    "category": svc.get("category", category),
                    "monthly_limit": svc.get("monthly_limit", "N/A"),
                    "description": svc.get("description", ""),
                })
    
    return summary


def check_free_tier_eligibility(provider: str, resources: list) -> dict:
    """
    Check if resources are within free tier limits.
    Returns eligibility status and details.
    """
    if provider != "aws":
        return {"eligible": False, "message": "Free tier check only available for AWS"}
    
    # This would integrate with the existing _check_free_tier_eligibility
    # For now, return basic info
    return {
        "eligible": True,
        "message": "Free tier eligibility check available",
        "services_checked": len(resources),
    }
